#!/usr/bin/env python3
"""Write config/macro_text.h, the key presses for each text macro.

Each macro NAME takes its text from $KB_MACRO_<NAME> or, failing that, from
macros/<name>.txt next to this script. Neither the text files nor the
generated header are committed.
"""
import os
import pathlib
import sys

MACROS = ['LCGRIND']

KEYS = {
    ' ': 'SPACE', '\n': 'RET', '!': 'EXCL', '"': 'DQT', '#': 'HASH', '$': 'DLLR',
    '%': 'PRCNT', '&': 'AMPS', "'": 'SQT', '(': 'LPAR', ')': 'RPAR', '*': 'ASTRK',
    '+': 'PLUS', ',': 'COMMA', '-': 'MINUS', '.': 'DOT', '/': 'SLASH', ':': 'COLON',
    ';': 'SEMI', '<': 'LT', '=': 'EQUAL', '>': 'GT', '?': 'QMARK', '@': 'AT',
    '[': 'LBKT', '\\': 'BSLH', ']': 'RBKT', '^': 'CARET', '_': 'UNDER', '`': 'GRAVE',
    '{': 'LBRC', '|': 'PIPE', '}': 'RBRC', '~': 'TILDE',
}

def key(c):
    if 'a' <= c <= 'z':
        return c.upper()
    if 'A' <= c <= 'Z':
        return f'LS({c})'
    if '0' <= c <= '9':
        return f'N{c}'
    return KEYS[c]

here = pathlib.Path(__file__).resolve().parent

def macro_text(name):
    var, path = f'KB_MACRO_{name}', here / 'macros' / f'{name.lower()}.txt'
    if var in os.environ:
        return os.environ[var], var
    if path.exists():
        return path.read_text().removesuffix('\n'), path.name
    print(f'WARNING: no text for macro {name}, set {var} or create {path}', file=sys.stderr)
    return '', 'nothing'

lines = ['// Generated by macro_text.py, do not commit']
for name in MACROS:
    text, source = macro_text(name)
    try:
        bindings = ' '.join(f'&kp {key(c)}' for c in text) or '&none'
    except KeyError as e:
        sys.exit(f'ERROR: no ZMK key for {e.args[0]!r} in macro {name}')
    lines.append(f'// MACRO_{name}_BINDINGS from {source}')
    lines.append(f'#define MACRO_{name}_BINDINGS {bindings}')

header = '\n'.join(lines) + '\n'
out = here / 'config' / 'macro_text.h'
if not out.exists() or out.read_text() != header:
    out.write_text(header)
